// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "kgax.h"

/////////////////////////////////////////////////////////////////////////////
// CKGAX

IMPLEMENT_DYNCREATE(CKGAX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CKGAX properties

CString CKGAX::GetCaption()
{
	CString result;
	GetProperty(DISPID_CAPTION, VT_BSTR, (void*)&result);
	return result;
}

void CKGAX::SetCaption(LPCTSTR propVal)
{
	SetProperty(DISPID_CAPTION, VT_BSTR, propVal);
}

CString CKGAX::GetText()
{
	CString result;
	GetProperty(DISPID_TEXT, VT_BSTR, (void*)&result);
	return result;
}

void CKGAX::SetText(LPCTSTR propVal)
{
	SetProperty(DISPID_TEXT, VT_BSTR, propVal);
}

long CKGAX::GetDocumentType()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CKGAX::SetDocumentType(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

CString CKGAX::GetDocumenFileName()
{
	CString result;
	GetProperty(0x2, VT_BSTR, (void*)&result);
	return result;
}

void CKGAX::SetDocumenFileName(LPCTSTR propVal)
{
	SetProperty(0x2, VT_BSTR, propVal);
}

long CKGAX::GetDocument3DDrawMode()
{
	long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CKGAX::SetDocument3DDrawMode(long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

BOOL CKGAX::GetDocument3DWireframeShadedMode()
{
	BOOL result;
	GetProperty(0x11, VT_BOOL, (void*)&result);
	return result;
}

void CKGAX::SetDocument3DWireframeShadedMode(BOOL propVal)
{
	SetProperty(0x11, VT_BOOL, propVal);
}

BOOL CKGAX::GetActiveKompasLoad()
{
	BOOL result;
	GetProperty(0x12, VT_BOOL, (void*)&result);
	return result;
}

void CKGAX::SetActiveKompasLoad(BOOL propVal)
{
	SetProperty(0x12, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CKGAX operations

LPDISPATCH CKGAX::GetKompasObject()
{
	LPDISPATCH result;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_DISPATCH, (void*)&result, NULL);
	return result;
}

void CKGAX::ZoomEntireDocument()
{
	InvokeHelper(0x5, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CKGAX::MoveViewDocument()
{
	InvokeHelper(0x6, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CKGAX::PanoramaViewDocument()
{
	InvokeHelper(0x7, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CKGAX::RotateViewDocument()
{
	InvokeHelper(0x8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CKGAX::OrientationDocument()
{
	InvokeHelper(0x9, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CKGAX::StopCurrentProcess(BOOL cancel)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 cancel);
}

long CKGAX::AddNewDocument(LPCTSTR fileName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		fileName);
	return result;
}

long CKGAX::AddNewEmptyDocument(long docType)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		docType);
	return result;
}

BOOL CKGAX::RemoveDocumentByIndex(long index)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		index);
	return result;
}

BOOL CKGAX::ActivateDocumentByIndex(long index)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xe, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		index);
	return result;
}

long CKGAX::GetActiveDocumentIndex()
{
	long result;
	InvokeHelper(0xf, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

BOOL CKGAX::InvalidateActiveDocument(BOOL erase)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x10, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		erase);
	return result;
}

long CKGAX::GetDocumentsCount()
{
	long result;
	InvokeHelper(0x13, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

BOOL CKGAX::DrawToDC(long dc, long left, long top, long width, long height)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x19, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		dc, left, top, width, height);
	return result;
}

void CKGAX::ZoomWindow(long type)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1a, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 type);
}

LPDISPATCH CKGAX::GetDocumentByIndex(long index)
{
	LPDISPATCH result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1b, DISPATCH_METHOD, VT_DISPATCH, (void*)&result, parms,
		index);
	return result;
}

void CKGAX::SetCurrentLibManager(long t)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x1c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 t);
}

void CKGAX::SetGabaritModifying()
{
	InvokeHelper(0x1d, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
