#if !defined(AFX_KGAX_H__C8357859_C2CD_49B6_A5AC_E99C4E8DD0AC__INCLUDED_)
#define AFX_KGAX_H__C8357859_C2CD_49B6_A5AC_E99C4E8DD0AC__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CKGAX wrapper class

class CKGAX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CKGAX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x6b943e71, 0x5ca2, 0x435d, { 0xaf, 0xa3, 0xd7, 0x81, 0x7b, 0x13, 0xac, 0xa2 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetCaption();
	void SetCaption(LPCTSTR);
	CString GetText();
	void SetText(LPCTSTR);
	long GetDocumentType();
	void SetDocumentType(long);
	CString GetDocumenFileName();
	void SetDocumenFileName(LPCTSTR);
	long GetDocument3DDrawMode();
	void SetDocument3DDrawMode(long);
	BOOL GetDocument3DWireframeShadedMode();
	void SetDocument3DWireframeShadedMode(BOOL);
	BOOL GetActiveKompasLoad();
	void SetActiveKompasLoad(BOOL);

// Operations
public:
	LPDISPATCH GetKompasObject();
	void ZoomEntireDocument();
	void MoveViewDocument();
	void PanoramaViewDocument();
	void RotateViewDocument();
	void OrientationDocument();
	void StopCurrentProcess(BOOL cancel);
	long AddNewDocument(LPCTSTR fileName);
	long AddNewEmptyDocument(long docType);
	BOOL RemoveDocumentByIndex(long index);
	BOOL ActivateDocumentByIndex(long index);
	long GetActiveDocumentIndex();
	BOOL InvalidateActiveDocument(BOOL erase);
	long GetDocumentsCount();
	BOOL DrawToDC(long dc, long left, long top, long width, long height);
	void ZoomWindow(long type);
	LPDISPATCH GetDocumentByIndex(long index);
	void SetCurrentLibManager(long t);
	void SetGabaritModifying();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_KGAX_H__C8357859_C2CD_49B6_A5AC_E99C4E8DD0AC__INCLUDED_)
